### ISSUE TITLE
DESeq2 input for Transcription factor activity inference in bulk RNA-seq

### ISSUE THREAD

**Issue by t1nnenissen** [saezlab/decoupleR#104]
Hi there,

Thanks for making this amazing toll available!

I have been trying to do a TF activity analysis of my bulk RNA-seq data following this guide: 
https://saezlab.github.io/decoupleR/articles/tf_bk.html

I have a few questions regarding the output from the DESeq2 analysis.

**1. For generating the heatmap - is it appropriate to use the output from the vsd function on the dds data?**  

**2. As input data for generating a plot as seen below (from the tutorial), is it appropriate to the use the 'stat' data generated from the Deseq2 analysis (see below)?** 

<img width="700" alt="Screenshot 2023-11-28 at 11 38 50" src="https://github.com/saezlab/decoupleR/assets/117599932/2507ade6-7b9b-41c4-ad77-0d20dc0e70b9">

<img width="607" alt="Screenshot 2023-11-28 at 11 41 09" src="https://github.com/saezlab/decoupleR/assets/117599932/e580f66c-23cf-4877-a3f7-4dd7dfd4cee8">

Best,
Tinne

**Comment by PauBadiaM** [comment]
Hi @t1nnenissen,

1) Indeed you can use the vst-transformed counts for the heatmap
2) Yes, to run enrichment analysis from `DESeq2` results we recommend to use their `stat` value since it informs both the direction of change (+ or -) and the significance of the change (the absolute magnitude of the value).

Hope this is helpful!
