### ISSUE TITLE
Pathway activity inference from scRNA-seq tutorial produces wrong results? 

### ISSUE THREAD

**Issue by kiwipeel** [saezlab/decoupleR#112]
Hi, 

I am analyzing single cell data. I've used your tutorial for pathway activity analysis tutorial in this link below: 
https://saezlab.github.io/decoupleR/articles/pw_sc.html

![DecoupleR](https://github.com/saezlab/decoupleR/assets/143732780/bfdebf39-52f8-4071-bcab-5253f7364a32)

It gave me these results and I think there is some problem with it. Neutrophil cluster shows very high expression of TNF but this cluster also has the lowest TNFa pathway activity. 

I also used tutorial on progeny's page and this time results give me the opposite for neutrophil cluster which is more accurate.

**Comment by PauBadiaM** [comment]
Hi @kiwipeel,

This could be biologically plausible since one thing is the expression of the TNFa ligand, and the other is the response to that signal which is what we infer with decoupleR. The differences observed are because old progeny uses a different enrichment method than `mlm`, you can try running `ulm` instead and see if they are comparable. Additional, you can always explore the downstream genes that are driving the response to a pathway with this [plot](https://saezlab.github.io/decoupleR/articles/pw_bk.html#visualization):
![image](https://github.com/saezlab/decoupleR/assets/44896790/9fc0bc63-f6bf-4108-b8e5-14c2ec198879)
You could get this plot by pseudobulking your expression at the cell type level and then plotting the pathway weights vs the observed expression. Hope this is helpful!
