### ISSUE TITLE
High TF activity with few significant genes

### ISSUE THREAD

**Issue by laurie-tonon** [saezlab/decoupleR#116]
Hi,

We use decoupleR with CollecTRI to quantify transcription factor activity in our bulk RNAseq data. We observe very strange results, where regulons have important activity with high statistical significance but when we look at the volcano plot of the genes only a handful are significant.
We use the DESeq2 stat value as input, and the consensus fonction.

Here is an example for a differential analysis:

![image](https://github.com/saezlab/decoupleR/assets/17641194/9e0e9d0d-6fc3-47f1-9a67-ddf9dd081814)

We see that the MYC regulon is highly repressed in our analysis.
But it we look at the volcano plot of its genes:

![image](https://github.com/saezlab/decoupleR/assets/17641194/fe3af403-976f-4655-9f98-3631251f56a0)

Only 4 genes are significant.

Same thing if we look at SP1:

![image](https://github.com/saezlab/decoupleR/assets/17641194/467a9b48-7c40-4056-9727-3d0eb6a17815)

As a result we are not very confident in the results obtained. 

Could you explain us how we can reach such enrichment score with so few genes?

Thanks a lot

**Comment by PauBadiaM** [comment]
Hi @laurie-tonon,

To correctly asses this you should plot the `stat` values instead of the `Log2FC` since this is what is used in the end to compute the enrichment score. Then, even if genes are not significantly changing, they are still used for the score calculation, this score just means that these genes are positively/negatively coordinated. One thing you could do is to filter by significance if it is important in your application, but I would advice against it since it reduces the background distribution of genes and results can become noisy.
Hope this is helpful!

**Comment by laurie-tonon** [comment]
Hi @PauBadiaM,

Thanks for your help. You are right, we should plot the `stat` values to be correct, as these are the ones used by decoupleR. But that won't change our conclusion that we don't trust the results, as many regulons are found significantly altered while very few genes are. 
We tried using another metric, such as `-log10*p-value`, but the results are also inconsistent. 
Our conclusion is that we can't perform an analysis of transcription factor activity like this if we have too few differentially expressed genes. We can only calculate a score per sample and compare distributions between our conditions.
Do you agree with this conclusion, or is there something else we haven't tried?

Thanks a lot

**Comment by PauBadiaM** [comment]
Hi @laurie-tonon,

Yes, computing scores per sample and then comparing distributions is also a valid strategy. However, I would also expect few hits if the results contain so many non-significant DEG.
