### ISSUE TITLE
Can I still use Findmarkers on dorothea results returned by wmean

### ISSUE THREAD

**Issue by Chengwei94** [saezlab/decoupleR#51]
Can I still use findmarkers on the score returned run_wmean? Do I need to scale through scaledata the data first before running it?  

Another qn: It seems that there are 11 methods to run in decoupleR. Is there any advise which is the best/what should I run for dorothea or progeny. It seems that the previous preferred method (viper) is no longer preferred?

**Comment by PauBadiaM** [comment]
Hi @Chengwei94 ,

Thanks for checking out the package! 

> Can I still use findmarkers on the score returned run_wmean? Do I need to scale through scaledata the data first before running it?

Scaling the data is optional but it helps to better identify differences across cells and yes you can run findmarkers to identify which TFs might be more active in certain groups.

> Another qn: It seems that there are 11 methods to run in decoupleR. Is there any advise which is the best/what should I run for dorothea or progeny. It seems that the previous preferred method (viper) is no longer preferred?

In the decoupleR [manuscript](https://academic.oup.com/bioinformaticsadvances/article/2/1/vbac016/6544613) we observed that methods based on linear models (`ulm` and `mlm`) or `norm_wmean` perform better therefore we recommend them over the rest. In the vignette we use `norm_wmean` because in this R implementation `ulm` and `mlm` take a while to run with more than 1000 samples. If you want to run them  faster I would recommend you to check the Python implementation of [decoupleR](https://decoupler-py.readthedocs.io/). Hope this was helpful.
