### ISSUE TITLE
Gene expression and TF activity 

### ISSUE THREAD

**Issue by parkjooyoung99** [saezlab/decoupleR#60]
My data result says that 'SMAD3' is activated in interested cluster. However, if I check the 'SMAD3' gene expression, no expression was seen. 

I thought if we have activated TF, than we should have gene expression since TF should be translated into the protein.
I wonder why I do not see the expression.

Thank you!

**Comment by PauBadiaM** [comment]
Hi @parkjooyoung99 

Thanks for checking out the package! 

If you are working with single-cell RNA-seq, it might be the case that the lack of expression is coming from the dropout effect known in this technology. Basically, genes that are lowly expressed due to the lack of deep sequencing are sometimes assigned 0s instead of a low value of expression. However, we know that even if you see expression of the TF, it doesn't mean that it's necessary active since many other factors can affect its regulatory output (closed chromatin, TF-TF cooperation, etc.). For this reason, we look at the "footprint" of TFs, their target genes, to see if they are overly expressed or not. Seeing that overall most SMAD3's targets are expressed means that the TF might have been active in that moment, independently if you see transcripts for it or not. Just in case, to reduce false positives one thing you could do is to check in the Human Protein Atlas if your TF is actually expressed in your tissue of interest. You can access HPA by running:
```R
hpa <- decoupleR::get_resource('HPA_tissue') # this might take some minutes
```

If you are working in bulk RNA-seq instead, then it might be the case that this is indeed a false positive. Again, one thing you could do is to filter out TFs that are not expressed in your tissue of interest according to the HPA.

Hope this was helpful! If you have more questions do not hesitate to ask
