### ISSUE TITLE
Using decoupleR across conditions

### ISSUE THREAD

**Issue by singhh5050** [saezlab/decoupleR#67]
Hi! I'm using a scRNA-seq dataset with cells from healthy breast tissue (normal condition) and cells from cancerous breast tissue (cancer condition). How would I go about performing pathway activity inference and transcription factor activity inference across conditions? I've followed the scRNA-seq vignettes on GitHub but I can't seem to figure out how I can look for pathways/TFs that have higher levels in cancer cells compared to healthy cells, for example. Is there a way to output pathways and TFs that are upregulated specifically in the cancer phenotype? Also, if I was interested in looking at biological activities in specific cell types, is there a way to do that? Thanks for your help!

**Comment by PauBadiaM** [comment]
Hi @singhh5050,

Sorry for the delayed response, I was on holidays.

To infer activities across conditions it's better to use contrast statistics. If you have enough samples (meaning patients, not number of cells), you can pseudobulk your samples per cell type and compute differential expression analysis across conditions and cell types (healthy vs disease) using your favorite statistical tool (deseq2, limma, edgeR, simple t-tests, etc.). The obtained statistic, for example t-values, can be used as input to decoupler. Here is an [example vignette](https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html), it's in python but the concept behind is the same.

In case you don't have enough true replicates (samples) and cannot pseudobulk your data, another way would be to estimate activities at the cell level, and then compare the activity between populations of cells between conditions per cell type.

Hope this is helpful! If you have more questions do not hesitate to ask.

**Comment by singhh5050** [comment]
Hi,

Is there code to run this in R?

**Comment by PauBadiaM** [comment]
Hi @singhh5050,

Unfortunately not yet. For single-cell we have decided to focus more in the python version for its better scalability compared to R. If I have time in the future I'll try to add more vignettes but this could take a while.
You could have a look at the [muscat vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/muscat/inst/doc/analysis.html#differential-state-ds-analysis), since it does pseudobulk and differential testing, then you could use these results as input to decoupler.

Hope this is helpful!
