### ISSUE TITLE
Discrepancy TF-Target database downloaded from DoRothEA and decoupleR

### ISSUE THREAD

**Issue by harimchun** [saezlab/decoupleR#68]
Hi, I am using decoupleR with my scRNA-seq data.

While inferring transcription factor activities using the DoRothEA, I found discrepancies in the database size.

If I download TF-Target information (Confidence level: A, B, C, D) using the DoRothEA library using the R code below,
```r
net_dorothea <- dorothea::dorothea_hs
net_dorothea %>% filter(confidence %in% c('A', 'B', 'C', 'D')) %>% pull(tf) %>% unique() %>% length()

```
I can get 361 unique TF information.

However, when I download TF-Target information (Confidence level: A, B, C, D) using the decoupleR library using the R code below, 
```r
net_decoupler <- decoupleR::get_dorothea(organism='human', levels=c('A', 'B', 'C', 'D'))
net_decoupler$source %>% unique() %>% length()

```

I can get 643 unique TF information.

Also, column names are different between the two databases. I don't know why these discrepancies occurred.

In this case, which database should I use to infer the transcription factor activities?

**Comment by PauBadiaM** [comment]
Hi @harimchun 

There are currently two versions of DoRothEA. In the original package we store the old one (`dorothea::dorothea_hs`) while in OmniPath we store the new one (which we call from decoupleR with `decoupleR::get_dorothea`). 

We recommend using the new one through decoupleR. In the future release of BioC we are going to update the `dorothea` package so that the two versions match.

**Comment by harimchun** [comment]
Thanks! I would use `decoupleR::get_dorothea`

Have a great day.
