### ISSUE TITLE
Pamgene S100 values to t-values

### ISSUE THREAD

**Issue by DuruTuncer** [saezlab/decoupleR#93]
Hello, I want to run decoupleR kinase analysis with the data obtained from pamgene. I have the S100 values and I'm not entirely sure how the t-values in the toy data were calculated. 

I would really appreciate if you could help me with this issue.

Thanks you.
```r
# insert reprex here
```

**Comment by PauBadiaM** [comment]
Hi @DuruTuncer,

Sorry, I am not familiar with pamgene S100 values. In case you want to infer kinase activity at the observation level (samples), they need to be somehow normalized so that they are comparable across samples. In case you want to infer differential kinase activity at the contrast level (condition A vs condition B), as long as they are centered around 0 and have positive and negative values they should work. Hope this is helpful!
