### ISSUE TITLE
get_collectri error

### ISSUE THREAD

**Issue by t1nnenissen** [saezlab/decoupleR#95]
Hi there, 

I have previously been successfully used DecupleR (and I love it!). However, yesterday I ran into an issue. 

Running the command:

net <- get_collectri(organism='human', split_complexes=FALSE)
 
I got the following error:

<img width="911" alt="Screenshot 2023-10-04 at 10 24 34" src="https://github.com/saezlab/decoupleR/assets/117599932/7f752a46-4bde-40c2-a8f8-6645aeee2de3">

Do you have idea what that might be due to? My decouple version is 2.7.1 and Omnipath is 3.9.8.

Best,
Tinne

**Comment by PauBadiaM** [comment]
Hi @t1nnenissen 

Thanks for opening this issue. @deeenes the right versions look alright, any idea what could be causing it?

**Comment by t1nnenissen** [comment]
@deeenes any ideas?

**Comment by deeenes** [comment]
Hello,

The first post is a bit contradictory for me, because it says `static_table` is not exported, while the version is 3.9.8, and in that version it was already exported.

In the next log we see that downloading something from omabrowser.org gives the same `bad value` error. It suggests that likely any call to `read_tsv` triggers the error. The alternative is that there is something common downstream and we see this error twice just by accident. But let's stay at the first version. Could you please try if the same error manifests when calling `read_tsv` directly?

```
library(readr)

example_url <-
	paste0(
		'https://omnipathdb.org/interactions?',
		'genesymbols=yes&datasets=collectri&organisms=9606&dorothea_levels=A,B',
		'&fields=evidences,sources,references,curation_effort&license=academic'
	)

result <- read_tsv(example_url, col_types = cols(), progress = FALSE)
```

If you see the error, please show us the traceback.

Also if the error pops up with `read_tsv`, let's check further: `readr::read_tsv` calls `httr` if an URL is provided, `httr` is built on `curl`. What happens if you call directly `httr::GET` or `curl::fetch_disk`?

```
library(httr)
library(curl)

resp <- httr::GET(example_url)
resp <- curl::curl_fetch_disk(example_url, tempfile())
```

`bad value` errors are unfortunately cryptic, it's difficult to find their reason: it can be running out of memory, null pointer, stack overflow, etc. It would be helpful to see the output of `sessionInfo` on your machine, after loading `OmnipathR`:

```
library(OmnipathR)
sessionInfo()
sessioninfo::session_info()
```

Also, can you confirm if the packages `readr`, `vroom`, `httr` and `curl` are all up-to-date? 

If this error persists in a reproducible manner, one next step could be to run R with debugger (`gdb`).

Best,
Denes

**Comment by t1nnenissen** [comment]
Hi Denes, 

Thanks a lot!

The issue is resolved now - I think it was due to an issue with the data.table package on my Mac!

Best,
Tinne
